[book]
title = "Het NLJong concept"
authors = ["Luka Leer"]
description = "Een platform voor Nederlandse jongeren om kennis te delen en te leren."
src = "docs"
language = "nl"
multilingual = false

[preprocessor.alerts]

[output.html]
theme = "theme"
smart-punctuation = true
git-repository-url = "https://github.com/NLJong/concept"
edit-url-template = "https://github.com/NLJong/concept/edit/main/{path}"
site-url = "https://concept.nlj.ong"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[output.linkcheck]
follow-web-links = true
