version: 3

tasks:
  setup:rust:
    internal: true
    desc: Set-up Rust
    run: once
    cmds:
      - platforms: [windows]
        cmd: winget install --interactive --id Rustlang.Rustup
      - platforms: [linux, darwin]
        cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    interactive: true
    status:
      - cargo --version

  setup:
    desc: Set-up environment
    cmds:
      - task: setup:rust

  install:rust:
    internal: true
    desc: Install Rust dependencies
    run: once
    preconditions:
      - msg: "Cargo is not installed"
        sh: cargo --version
    cmds:
      - cmd: cargo install mdbook mdbook-alerts mdbook-linkcheck
      - cmd: cargo install mdbook-pdf --features fetch

  install:python:
    internal: true
    desc: Install Python dependencies
    run: once
    preconditions:
      - msg: "PIP is not installed"
        sh: pip --version
    cmds:
      - cmd: pip install mdbook-pdf-outline

  install:
    desc: Install dependencies
    cmds:
      - task: install:rust
      - task: install:python

  build:
    desc: Build the project
    deps:
      - task: install
    cmds:
      - cmd: mdbook build

  serve:
    desc: Serve the project
    deps:
      - task: install
    cmds:
      - cmd: mdbook serve
    interactive: true
