name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set-up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set-up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Set-up Python
        uses: actions/setup-python@v4
        with:
          cache: pip

      - name: Set-up Task
        uses: arduino/setup-task@v2

      - name: Build book
        run: task build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: book/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Set-up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
